// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtN4iyqw3oMX5DSEjs_l9nJ-pJeH3jT00',
    appId: '1:719862810640:web:ca191a1d69fa3fb268e295',
    messagingSenderId: '719862810640',
    projectId: 'spotidupe01',
    authDomain: 'spotidupe01.firebaseapp.com',
    storageBucket: 'spotidupe01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlkkA65GfCtzFyoru1w5YR_ggWmnggOw',
    appId: '1:719862810640:android:785a64d7e6aeba7668e295',
    messagingSenderId: '719862810640',
    projectId: 'spotidupe01',
    storageBucket: 'spotidupe01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrpMe_RK2Z_whGYjWKvNS--N7k892bKnI',
    appId: '1:719862810640:ios:8ee41b98f83133c368e295',
    messagingSenderId: '719862810640',
    projectId: 'spotidupe01',
    storageBucket: 'spotidupe01.appspot.com',
    iosBundleId: 'com.example.spotidupe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrpMe_RK2Z_whGYjWKvNS--N7k892bKnI',
    appId: '1:719862810640:ios:8ee41b98f83133c368e295',
    messagingSenderId: '719862810640',
    projectId: 'spotidupe01',
    storageBucket: 'spotidupe01.appspot.com',
    iosBundleId: 'com.example.spotidupe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtN4iyqw3oMX5DSEjs_l9nJ-pJeH3jT00',
    appId: '1:719862810640:web:edd8c02b93447aa068e295',
    messagingSenderId: '719862810640',
    projectId: 'spotidupe01',
    authDomain: 'spotidupe01.firebaseapp.com',
    storageBucket: 'spotidupe01.appspot.com',
  );

}